version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/Bharathkumarraju/hello-circleci
    steps:
      - checkout
      - run: echo "Hello World!"st -v ./...
workflows:
  version: 2
  workflow:
    jobs:
      - build