# Top of file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/Bharathkumarraju/hello-circleci
    steps:
      - checkout  # Checks out the source code
      - run: echo "Hello World!"st -v ./...
      - run: go get -d ./...
      - run:
          name: Build the executable
          command: |
            echo "Hello this is build step"
            go build
      - persist_to_workspace:
          root: .  # Persist current working directory
          paths: ./*  # glob. Will persist everything in a folder
      - store_artifacts:
          path: ./hello-circleci  # executable
test:
  docker:
    - image: circleci/golang:1.11.1
  working_directory: /go/src/github.com/Static-Void-Academy/circleci-hello
  steps:
    - attach_workspace:
        at: .
    - checkout  # Checks out the source code
    - run: go get -d ./...
    - run: go test

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test
           requires:
               - build