# Top of file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/Bharathkumarraju/hello-circleci
    steps:
      - checkout # Checks out the source code
      - run: echo "Hello World!"st -v ./...
      - run: go get -d ./...
      - run:
          name: Build the executable
          command: |
            echo "Hello this is build step"
            go build
      - store_artifacts:
          path: ./hello-circleci# executable